### PR TITLE
Use gb

### PR DESCRIPTION
**Pull request by guilhem**
To help managing code and vendoring, I often use [gb](https://getgb.io/).

It can be used like that (after installing gb)

``` sh
# restore dependency as listed in vendor/manifest
gb vendor restore
gb build
```

### CODE REVIEW

**Comment by danderson** [comment]
Hmm, what do you think of godep instead of gb?

I'm not a fan of gb because it doesn't play nicely with the builtin `go` tool, so it forces anyone who wants to build pixiecore to use a specific build tool. In contrast, godep manages the dependencies, but stays compatible with `go install` for people who don't care. It also keeps the import paths clean for packages (github.com/danderson/pixiecore/tftp vs. github.com/danderson/pixiecore/src/tftp), which is a nice cosmetic touch.

However, I've never used any of these tools (except for the builtin `go` tool), so I welcome your opinion :)

**Comment by guilhem** [comment]
I really found `godep` very annoying to use. But yes `gb` change the way to import package internally and is incompatible with standard go tools...
Personally I prefer an easy way to build, manage dep and building with gb and libraries on another repo (compatible with go get). But with a CI (like travis) who is releasing binaries like there: https://github.com/themecloud/etcd2envfile/releases
But that my point of view... who can be really wrong especially with new go1.6 vendor

So... I really don't know...

**Comment by guilhem** [comment]
Some voices tell me that https://github.com/Masterminds/glide is even better ;)

**Comment by guilhem** [comment]
#24 supersede this one

**Pull request closed without merging**
